format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$python\
$cmd_duration $jobs $time\
$line_break\
$character"""

palette = "mycolor"

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
style = "fg:muted_rose_pink"

[fill]
symbol = " "

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
success_symbol = "[❯](cornflower_blue)"
error_symbol = "[❯](deep_fuchsia)"
vicmd_symbol = "[❮](turquoise)"

[directory]
format = "[ $path ]($style)"
style = "fg:muted_blue_shade bg:muted_rose_pink"
truncation_length = 4
truncate_to_repo = false

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Pictures" = " "

[git_branch]
format = '[[ $symbol $branch ](fg:muted_rose_pink bg:muted_blue_shade)]($style)'
style = "bg:muted_blue_shade"
symbol = " "

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bold yellow"

[git_status]
format = '[[($all_status$ahead_behind )](fg:muted_rose_pink bg:muted_blue_shade)]($style)'
style = "bg:muted_blue_shade"

[git_metrics]
disabled = false

[jobs]
symbol = ""
style = "bold red"
number_threshold = 1
format = "[$symbol]($style)"

[cmd_duration]
format = "[$duration]($style)"
style = "cyan"

[memory_usage]
symbol = " "

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:muted_rose_pink bg:muted_blue_shade)]($style)'

[palettes.mycolor]
muted_rose_pink = "#e6a5a3"
muted_blue_shade = "#1d2230"
turquoise = "#00bf8f"
deep_fuchsia = "#d11550"
deep_pinkish_red = "#b31252"
cornflower_blue = "#636ff7"
